### ISSUE TITLE
ESLint checker on pull request.

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/suma#13]
I am creating a lint validator when the repository receives a pull request and I would like to check if the lint file below meets the needs of the repository.

The file is what I use today in the repository and in any other repository where I made pull requests on herbsjs. But I would like to check with you if it meets the need or if you need to put something new.

```
{
  "env": {
    "commonjs": true,
    "es6": false,
    "node": true
  },
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly"
  },
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "rules": {
    "semi": ["error", "never"],
    "func-names": 0,
    "no-param-reassign": 0,
    "no-multi-str": 0,
    "consistent-return": 0
  }
}
```

**Comment by thgpdr** [comment]
Nice. 
I would like to add these rules as well. I use as a standard in my projects:

"no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
"no-console": ["error", { allow: ["tron"] }]

**Comment by jhomarolo** [comment]
> 
> 
> Nice.
> I would like to add these rules as well. I use as a standard in my projects:
> 
> "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
> "no-console": ["error", { allow: ["tron"] }]

I believe that these rules make a lot of sense to be added, thanks @thgpdr !
