### ISSUE TITLE
The library should have documentation for checkers

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/suma#37]
**Is your feature request related to a problem? Please describe.**
Suma checkers is a great thing, but we do not have those documented, neither in the readme or into the website

**Describe the solution you'd like**
A clear and concise documentation about how to use each checker.

**Comment by maikvortx** [comment]
WIP!

**Comment by maikmb** [comment]
Issues: 
- https://github.com/herbsjs/herbsjs.github.io/issues/94

PRs: 
- https://github.com/herbsjs/suma/pull/43
- https://github.com/herbsjs/herbsjs.github.io/pull/95
