### ISSUE TITLE
Checks if value is a DOM element.

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/suma#39]
**Is your feature request related to a problem? Please describe.**
Suma should if a property is a DOM element

**Describe the solution you'd like**
In order to check whether a JavaScript object is a DOM object, we need to check whether the given JS object is of an Element type Object.

**Describe alternatives you've considered**
We could use the nodeType WebAPI (https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType) to check if the value is a DOM element like that:

```javascript

function isDOMElement(value) {
      return value && value.nodeType === 1 || false;
    }

```

**Comment by dalssoft** [comment]
What's the use case here?

**Comment by jhomarolo** [comment]
For two scenarios, not very critical.

1 - For tests in herbsshelf, since we already do the manual checking of the generated HTML result.

2 - For gotu, when it is used on the front-end in the creation of classes that deal with HTML type fields (pdf generation for example).

**Comment by dalssoft** [comment]
the purpose of suma is to guarantee validations for entities in general. particularly, I don't like the direction we're taking suma as a generic validation and checks lib, especially for very simple uses or outside the backend.

**Comment by italojs** [comment]
I agree with the dalssoft, I'm not sure if use the herbs into frontend is a good ideia.

**Comment by dalssoft** [comment]
> I'm not sure if use the herbs into frontend is a good ideia.

Just to make sure, that is not what I said. Herbs has the potential to be used in front end (and actually has already been used successfully) given its focus on the domain and not on the infrastructure. It is totally fine to model your domain (or part of it) on the front end (ex: SPAs, PWAs, etc). 

I just don't think that such infrastructure (DOM, browser, etc) validation should be inside suma.

I'm closing this issue for the reason given above.
