### ISSUE TITLE
Create a error translator

### ISSUE THREAD

**Issue by m7vicente** [herbsjs/suma#9]
What do you think to create a feature or one library to translate the errors from Gotu object, into
strings that we can really show to users like errors?

The idea is to provide a list whit the Suma errors and the correct traduction in some real language, the function uses those list and we pass attributes with errors who will be translated to a string.

Gotu errors attribute return
`password: [ { isTooShort: 6 } ] `

translated errors could be like
`Password is too short the expected is 6` or `Senha muito curta o esperado 6`

**Comment by dalssoft** [comment]
go for it! we might even incorporate it on herbs project...

suggestions: 
- i18n from the beginning
- if it can be used on front-end, think a way to reduce the size of the package by including only the selected languages

**Comment by m7vicente** [comment]
we can close this issue since we have been implemented [suma2text](https://github.com/herbsjs/suma2text)
